### ISSUE TITLE
gulp serve throws an error

### ISSUE THREAD

**Issue by rebmullin** [scottnath/generator-pattern-library#1]
`gulp build`  seems to run fine (?) but when I run `gulp serve`, i see the following issue: http://grab.by/JYZO

its seems that the patternlab isn't loading everything(?)  is anyone else have this issue?

**Comment by scottnath** [comment]
@rebmullin can you please revisit and see if you're still getting this error?

**Comment by rebmullin** [comment]
@scottnath I think this is fine now. I didn't realize composer was not installed and i think this was causing this issue..

**Comment by scottnath** [comment]
@rebmullin ok - closing issue
