### ISSUE TITLE
Generator needs to be compatible with Node v4+

### ISSUE THREAD

**Issue by e2tha-e** [scottnath/generator-pattern-library#12]
Generator fails when trying to build with Node v4.0.0. We need this to be present- and future-compatible. After just a few days of writing es6 code, I personally cannot go back to es5 syntax for oo js, so I'm sticking with node v4 on my dev machine.

Error on `yo pattern-library`:
gyp: /Users/Hyunho/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.8

> fsevents@0.3.8 install /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp: /Users/Hyunho/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

> utf-8-validate@1.1.0 install /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp: /Users/Hyunho/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.8

> bufferutil@1.1.0 install /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp: /Users/Hyunho/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
 /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things

> bufferutil@1.1.0 install /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp: /Users/Hyunho/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

> utf-8-validate@1.1.0 install /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp: /Users/Hyunho/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0
## npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> node-sass@3.3.2 install /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> node-sass@3.3.2 postinstall /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

`/Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node` exists.
 testing binary.
## Binary is fine; exiting.

> node-sass@2.1.1 install /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-importer/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.0/binding.node

> node-sass@2.1.1 install /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-library-utilities/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.0/binding.node

> node-sass@2.1.1 postinstall /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-importer/node_modules/node-sass
> node scripts/build.js

gyp: /Users/Hyunho/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-importer/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-importer/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-importer/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-importer/node_modules/node-sass
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
Build failed

> node-sass@2.1.1 postinstall /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-library-utilities/node_modules/node-sass
> node scripts/build.js

gyp: /Users/Hyunho/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-library-utilities/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-library-utilities/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-library-utilities/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/Hyunho/Sites/PatternLibrary/generator-pattern-library/node_modules/pattern-library-utilities/node_modules/node-sass
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
Build failed

**Comment by e2tha-e** [comment]
@conortm @beynya @sergesemashko @rebmullin @nikkiana @gvorbeck ^

**Comment by scottnath** [comment]
@e2tha-e seems like a specific issue with node-sass. Looks like they've made the changes, but haven't made an official release of those changes yet and thus they're not getting picked up by gulp-sass.

Could you try to change gulp-sass' package.json in node_modules, deleting gulp-sass' node_modules directory and doing a new `npm install` to see if that would fix this issue?

**Comment by scottnath** [comment]
I have been trying to get to the bottom of this error. 

Have any of you found a solution to this node-sass/libsass bindings issue?

note: I've added NVM and have the ability to have multiple versions of node on my machine:
http://michael-kuehnel.de/node.js/2015/09/08/using-vm-to-switch-node-versions.html
works really well

**Comment by scottnath** [comment]
@conortm @beynya @sergesemashko @rebmullin @nikkiana @gvorbeck @e2tha-e ^

**Comment by scottnath** [comment]
@conortm @beynya @sergesemashko @rebmullin @nikkiana @gvorbeck @e2tha-e ^

This is fixed now. It was an issue with a couple of sub-modules using an older version of node-sass.

Please update your generator by running:

`npm install -g generator-pattern-library`
