### ISSUE TITLE
php patternlab/core/console --generate throws error

### ISSUE THREAD

**Issue by e2tha-e** [scottnath/generator-pattern-library#4]
it doesn't appear that pattern lab has been set-up yet...
please install pattern lab's dependencies by typing: php core/bin/composer.phar install...

**Comment by scottnath** [comment]
@sergesemashko did we determine this was an issue as to whether composer was installed globally?

@conortm: task to create:
to do: create composer installation instructions

**Comment by scottnath** [comment]
@e2tha-e are you still seeing this issue?

**Comment by e2tha-e** [comment]
@scottnath Yes, I pulled the latest from master, and am still getting the same error.

**Comment by scottnath** [comment]
Did we determine this was an issue with composer?

Can you please attempt the basic composer installation instructions to see if the install works?
https://github.com/pattern-lab/edition-php-twig-standard#2-install-the-standard-edition-for-twig

**Comment by sergesemashko** [comment]
@e2tha-e, 
1. try to install composer globally by this command: `curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer`
2. Then remove ./patternlab folder
3. Try `gulp build`

And let me know if you still have patternlab not running

**Comment by e2tha-e** [comment]
@scottnath @sergesemashko This still fails in OS X 10.9.5 Mavericks using PHP v5.4.43 and Composer v1.0.0-alpha9.

However, the gulp build works correctly on OS X 10.10.5 Yosemite using PHP v5.5.27 and Composer v1.0-dev

**Comment by scottnath** [comment]
I am running:

OSX 10.10.4 
Composer version 1.0.0-alpha10 2015-04-14 21:18:51
PHP 5.4.43 (cli) (built: Jul 13 2015 17:16:09)

@sergesemashko @conortm @rebmullin : What are your versions for these?
@e2tha-e would a requirement to use 10.10.4 + be a hinderance for you?

**Comment by e2tha-e** [comment]
@scottnath I'm fine with 10.10.4+ being a minimum requirement since my dev box is at 10.10.5.

**Comment by scottnath** [comment]
@e2tha-e great...so can this issue be closed? The system is working for you now?

**Comment by e2tha-e** [comment]
@scottnath I think this issue can be closed.
