### ISSUE TITLE
creating pattern has undefined message

### ISSUE THREAD

**Issue by rebmullin** [scottnath/generator-pattern-library#7]
hey @scottnath  - when i create a pattern, it seems to work okay but i get the following message in terminal: http://grab.by/Khqg - see bottom messages

not sure really if this is an issue but didn't seem right...

**Comment by scottnath** [comment]
That's a bug! Minor one...but noted...

**Comment by rebmullin** [comment]
@scottnath  - confirmed fixed by PR :+1:
