### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by rebmullin** [scottnath/generator-pattern-library#9]
hey @scottnath  a few more questions:
- is there a way to include one pattern in another - like for example promo inside of carousel?
- if i wanted to modify promo pattern - how would i do that? would i just create my own promo version b/c current promo is unmodifiable? 
- any clue why readme (created when I run "yo pattern-library" i believe) is not the same as repo’s version..?

**Comment by scottnath** [comment]
## include one pattern in another

as a twig include, yes.
- [how to twig includes](http://twig.sensiolabs.org/doc/tags/include.html)
- [example pattern with include](https://github.com/pattern-library/pattern-library/blob/master/patterns/molecules/media/figure-image/figure-image.twig)

## modify promo pattern (or any pattern in NPM)

Right now, you just need to copy it down to your `./patterns` directory.

We will be adding this as a feature to the Yeoman generator

## readme

not sure what you mean. can you show an example file @rebmullin ?

**Comment by rebmullin** [comment]
okay cool @scottnath  - maybe we can put this in the readme or wiki..?

regarding the last point - see my readme : http://grab.by/KhGW - it looks like it's an outdated version, no?

**Comment by scottnath** [comment]
@rebmullin which part is outdated? Other than the bottom with `command TBD`?

**Comment by rebmullin** [comment]
@scottnath  -  other than the bottom...the top is different altho similar... not a big deal but just noticed it was different and wasn't sure if this should be the same..

**Comment by scottnath** [comment]
sorry @rebmullin ...confused...this file is different from what file?

**Comment by rebmullin** [comment]
disregard 3rd question about the readme being different

aslso created PR #10 for readme updates to give on other 2 questions..

closing issue..

//cc @scottnath
